### ISSUE TITLE
Update from 2.0.2 to 2.0.3 have non-documented breaking changes

### ISSUE THREAD

**Issue by Manoz** [optimistdigital/nova-locale-field#2]
Hello,

The update between version 2.0.2 and version 2.0.3 of your package contains a "breaking change" that has not been documented.

This creates issues if you still use the `make()` method.

Be careful with semver, it can cause a lot of problems later on.

I think it should at least be documented in the release :)
Your readme.md should be edited too

**Comment by Tarpsvo** [comment]
Ah shit, sorry about that!

Nova 3.1 added their own `make()` function to the Filter in Nova 3.1 which caused an exception. For some reason, I thought it's okay to remove it from LocaleFilter altogether. I re-added it again, with the Nova 3.1 signature so it doesn't crash.

Sorry about that! Wasn't an intentional breaking change, just a fix I didn't think through.

Fix released in 2.0.4. Good luck!

**Comment by Manoz** [comment]
No problems. Thanks for your fix :)
